.circleci/config.yml
The default release title created via `gh` does not fit with our standards, _e.g._ `<release>: <commit title>` instead of `<release>`.
Add the `-t` option to the `gh release create` command.
=> 👷(project) fix release title

CHANGELOG.md, docker-compose.yml, src/dashboards/videos/details.jsonnet
The video view count could be a useful indicator in the video details dashboard.
add two simple gauge panels to show the number of video views and and the number of distinct viewers.
=> ✨(videos) add video views counter panels

CHANGELOG.md, src/dashboards/videos/details.jsonnet
Teachers need to know how much is a video completely viewed. It helps to know about the relevance of the video in a course (if it needs to be reviewed, replaced or kept).
This panel shows the number of complete views for a specific video of a course session.
=> ✨(dashboard) add complete video views panel

.circleci/config.yml, CHANGELOG.md, Makefile, bin/jsonnet-lint, src/dashboards/videos/common.libsonnet, src/dashboards/videos/course.jsonnet, src/dashboards/videos/statements.jsonnet
We want dedicated dashboards to display statistics about videos in a course.
Add course and statements dashboards
=> ✨(dashboard) add courses and statements dashboards

CHANGELOG.md, etc/grafana/provisioning/datasources/mysql.yaml, src/dashboards/platform/general.jsonnet
To get general platform statistics such as number of users, courses, enrollments... the database from edxapp has to be configured as a datasource.
=> ✨(datasources) add datasource configuration for edxapp mysql database

src/dashboards/common.libsonnet, src/dashboards/videos/common.libsonnet, src/dashboards/videos/course.jsonnet, src/dashboards/videos/details.jsonnet, src/dashboards/videos/statements.jsonnet
Dashboard pages, as they are continuously improved contained more and more panels. 
Jsonnet code associated with is becoming huge. 
Some fields are used many times through several panels. 
Following #14 pull request, Details dashboard file is reorganized with the `common.libsonnet` file.
=> Clean dashboard code

CHANGELOG.md, env.d/grafana, etc/grafana/provisioning/datasources/elasticsearch.yaml
Potsie's users are supposed to login to potsie using a SSO workflow thanks to the Keycloak platform. An example configuration to test locally this workflow would be warmly welcome.
1. This PR depends on: https://github.com/openfun/learning-analytics-playground/pull/10
2. Note that during this work, I also had to fix the ES data source configuration to fit with recent changes in the Ralph project (we now use datastreams).
=> Configure SSO with keycloak

env.d/grafana
When roles fetching fails after an oauth authentication, it's hard to debug the authentication process.
=> ⚡️(project) allow oauth authentication debugging

Makefile, docker-compose.yml, env.d/app
Remove unnecessary code in makefile and docker-compose
We could let an empty file `env.d/app` to use it as template if someone needs to register custom environment variable in the `app` container, but this can lead to a misunderstanding of the container execution requirements.
=> 🔥(project) Cleanup unnecessary code

.circleci/config.yml
Plugins are still not distributed with potsie packages.
We need to enforce paths that must persist to the current workspace and jobs dependencies to ensure that the release will also ship plugins.
=> 🐛(project) fix plugins packaging

src/dashboards/teachers/course.jsonnet
The minimum count that can be displayed in the panel of the statistics table for the course overview table was set 0. For Grafana, a such setting implies to display results for all statements from the elasticsearch which does not fit to our expectations as the datasource contains all courses from the platform. 
It has been set to 1 so that it fits to the request based on the course key and only displays data related to this key.
=> 🐛(provisioning) fix min count for course video statistics table

CHANGELOG.md, fixtures/mysql/edxapp.sql
For now, the datetime of courses used in the demonstration were hard coded. As the demonstration will evolve among time, it was proper to adapt the start and end dates to the current datetime. 
They have been set with a 2-month delta thanks to [DATE_ADD and DATE_SUB functions from mysql](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-add).
=> ⚡️(datasource) fix demonstration courses datetimes

CHANGELOG.md, env.d/grafana, scripts/users-permissions.sh, src/dashboards/common.libsonnet, src/dashboards/teachers/course.jsonnet, src/dashboards/teachers/details.jsonnet, src/dashboards/teachers/home.jsonnet, src/hooks/post-deploy
Some details needed to be improved for users experience.
=> Improve teachers teams UX 

CHANGELOG.md, Makefile, docker-compose.yml, scripts/users-permissions.sh
We need to stay up-to-date in grafana/elasticsearch releases.
During this work, I've also identified two bugs:
=> Maintenance chores

CHANGELOG.md, docker-compose.yml
Multiple vulnerabilities have been detected in the version 8.5.3 :
https://www.cert.ssi.gouv.fr/avis/CERTFR-2022-AVI-649/
Upgrade grafana to the latest release:
https://github.com/grafana/grafana/releases/tag/v9.0.5
=> ⬆️(project) upgrade grafana to 9.0.5

.gitlint.d/gitlint_emoji.py, LICENSE.md, src/plugins/packages/stacked-barchart/LICENSE, src/plugins/packages/stacked-barchart/package.json, src/plugins/packages/stacked-barchart/src/plugin.json
The GIP FUN-MOOC has been renamed France Université Numérique since a few years.
Replace each occurence of GIP FUN-MOOC with France Université Numérique
=> 📝(project) update copyright holder

.circleci/config.yml
`buildpack-deps` images are now deprecated. Following CircleCI
recommendation, we've switched them to base convenience images.
References:
[1] https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
[2] https://circleci.com/developer/images/image/cimg/base
gitlint-ignore: all
- Use cimg images
- Add login to Dockerhub step
=> Update deprecated convenience images

CHANGELOG.md, docker-compose.yml
Dashboard rendering was failing as configuration for ralph service was
incorrect. Naming for environment variables has changed.
Fix environment variables names in Docker-compose.
Grafana has been upgraded too and ralph is now pinned to the last published
version (not latest anymore).
=> Fix dashboard rendering

CHANGELOG.md, src/dashboards/teachers/course.jsonnet
Viewers computation was summing the number of unique views per video in a given
course which gives sometimes a metric higher than the number of enrolled users
in a course !
Change the request to count the number of views grouped by
`actor.account.name.keyword` and apply the count reducer function on this field.
=> 🐛(provisioning) fix viewers computation

CHANGELOG.md, docker-compose.yml, src/dashboards/common.libsonnet, src/dashboards/teachers/common.libsonnet, src/dashboards/teachers/course.jsonnet, src/dashboards/teachers/details.jsonnet, src/dashboards/utils.libsonnet
Until now, an user aggregation was used for viewers metric computation. But with
elasticsearch datasource type, the count reducer function is limited to 500
inputs. Nevertheless, lots of videos count more than 500 users.
To overcome this bug from elasticsearch, the cardinality metric is applied on viewed 
statements and the aggregation is made on `context.contextActivities.parent.id`
(i.e. course session ID).
=> Modify viewers aggregation

CHANGELOG.md, env.d/grafana
When deploying latest release of Potsie (with Grafana 10.X), the following error messages appears when signing in: `Login Failed - User sync failed`. 
It seems that it is due to a patch made in 10.1 release to fix a security issue. A configuration flag is necessary to get user sync from Keycloak auth provider.
See security issue documentation: https://grafana.com/blog/2023/06/22/grafana-security-release-for-cve-2023-3128/
=> Fix "user sync failed" login bug

CHANGELOG.md, README.md, docker-compose.yml, src/dashboards/teachers/course.jsonnet, src/dashboards/teachers/details.jsonnet
Previously, queries for course and details dashboards were not explicitly scoped to a single course, potentially exposing analytics from multiple courses if a video would be reused.
This change ensures that dashboard queries are restricted to the context of the currently selected course.
_On a side note, improving the README and fixing a docker compose warning._
=> 🔒️(provisioning) restrict video analytics to current course context
